config/routes.rb
Rails.application.routes.draw do

  resources :questions, only: [ :new, :create, :index, :show ] do
    resources :answers, only: [ :create ]
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :question

  validates :description, length: { minimum: 50 }

end

app/models/question.rb
class Question < ActiveRecord::Base

  has_many :answers


  validates :title, length: { minimum: 40 }
  validates :description , length: { minimum: 150 }

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController


###################
  #METHOD / ROUTES
###################
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)
    redirect_to question_path(@question)

  end




############
  #METHODS
############


private

  # this is so that people cant break in and hack your stuff. follow the format!

  def answer_params
    params.require(:answer).permit(:description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController


###################
  #METHOD / ROUTES
###################

  def index
    @questions = Question.all.order(updated_at: :desc)
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to questions_path
    else
      render 'new'
    end
  end




############
  #METHODS
############


private


  # this is so that people cant break in and hack your stuff. follow the format!
  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/index.html.erb
<h1>Questions#index</h1>

<%= link_to "New Question", new_question_path %>

<ul>
<% @questions.each do |question| %>
    <li> <%= link_to question.title, question_path(question)  %> </li>
<% end %>
</ul>

app/views/questions/new.html.erb
<h1> Ask A Question </h1>


<%= form_for @question  do |f| %>

  <% if @question.errors.any?  %>
    <ul>
      <% @question.errors.full_messages.each do |message|%>
        <li> <%= message %> </li>
      <% end %>
    <ul>
  <% end %>


<div>
  <%= f.label :title %>:
  <%= f.text_field :title %>
</div>
<div>
  <%= f.label :description %>:
  <%= f.text_field :description %>
</div>
  <%= f.submit %>

<% end %>

app/views/questions/show.html.erb
<h1> TEST </h1>
<%= @question.title %>
<%= @question.description %>


<h2>try and answer:</h2>
<%= form_for([@question, @question.answers.build]) do |f| %>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.submit %>

  </p>
<% end %>

<ul>
<p>Previous Answers</p>
<% @question.answers.each do | answer |%>
  <li><%= answer.description %> </li>
<% end %>
</ul>